### ISSUE TITLE
Currency pairs crash

### ISSUE THREAD

**Issue by olliethedev** [obsantos/MarketBot#2]
Currency pair conversion seems broken.
example : 
`$CAD-USD`

gives the following error:
```
Traceback (most recent call last):
  File "stock.py", line 80, in <module>
    main()
  File "stock.py", line 76, in main
    details = query_symbol_details(args.symbol)
  File "stock.py", line 48, in query_symbol_details
    result = response['quoteResponse']['result'][0]
IndexError: list index out of range
```

**Comment by obsantos** [comment]
Fixed on https://github.com/obsantos/MarketBot/pull/1

**Comment by olliethedev** [comment]
About time....
