### ISSUE TITLE
Crash on ETFs and Cryptocurrency quoteTypes

### ISSUE THREAD

**Issue by obsantos** [obsantos/MarketBot#3]
Example

`python3 stock.py -s ZAG.TO`

 returns
```
Traceback (most recent call last):
  File "/Users/obustosantos/Development/Personal/MarketBot/stock.py", line 91, in <module>
    main()
  File "/Users/obustosantos/Development/Personal/MarketBot/stock.py", line 87, in main
    details = query_symbol_details(args.symbol)
  File "/Users/obustosantos/Development/Personal/MarketBot/stock.py", line 62, in query_symbol_details
    price = get_price_for_market_state(state, result)
  File "/Users/obustosantos/Development/Personal/MarketBot/stock.py", line 40, in get_price_for_market_state
    "current": result['postMarketPrice']['fmt'],
KeyError: 'postMarketPrice'
```
same for
`python3 stock.py -s BTC-USD`

In both cases the response has `'quoteType': 'ETF'` and `'quoteType': 'CRYPTOCURRENCY'` instead of `'quoteType': 'EQUITY'` and it has less fields than an equity response.

Example of response:

```
{'quoteResponse': {'result': [{'fullExchangeName': 'Toronto', 'symbol': 'VRE.TO', 'gmtOffSetMilliseconds': -14400000, 'language': 'en-US', 'regularMarketTime': {'raw': 1635364770, 'fmt': '3:59PM EDT'}, 'regularMarketChangePercent': {'raw': 0.052674364, 'fmt': '0.05%'}, 'quoteType': 'ETF', 'tradeable': False, 'regularMarketPreviousClose': {'raw': 37.97, 'fmt': '37.97'}, 'exchangeTimezoneName': 'America/Toronto', 'regularMarketChange': {'raw': 0.020000458, 'fmt': '0.02'}, 'exchangeDataDelayedBy': 15, 'firstTradeDateMilliseconds': 1352385000000, 'exchangeTimezoneShortName': 'EDT', 'regularMarketPrice': {'raw': 37.99, 'fmt': '37.99'}, 'marketState': 'POST', 'market': 'ca_market', 'quoteSourceName': 'Delayed Quote', 'priceHint': 2, 'sourceInterval': 15, 'exchange': 'TOR', 'shortName': 'VANGUARD FTSE CDN CAPPED REIT I', 'region': 'US', 'triggerable': True, 'longName': 'Vanguard FTSE Canadian Capped REIT Index ETF'}], 'error': None}}
```

**Comment by obsantos** [comment]
For indexes also failing:

`python3 stock.py -s DJI`
returns `'quoteType': 'ECNQUOTE'`

`python3 stock.py -s ^DJI` (Dow jones)
returns `'quoteType': 'INDEX'`

**Comment by obsantos** [comment]
Fixed in https://github.com/obsantos/MarketBot/commit/42012ef29121183c30cbeb88c5f7988c798ce0ad and https://github.com/obsantos/MarketBot/commit/eea2d160f34a34c720428d9efc4a0dc41aa9539f
